Nginx
server {
    listen 80;

    # 1. ถ้าเรียก URL ที่ขึ้นต้นด้วย /api ให้ส่งไปที่ Container ของ Backend (พอร์ต 5000)
    location /api/ {
        proxy_pass http://backend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 2. นอกเหนือจากนั้น (หน้าเว็บปกติ) ให้ส่งไปที่ Container ของ Frontend (พอร์ต 80 ภายในของ Nginx ตัวเล็ก)
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # สำหรับ React Router เพื่อไม่ให้หน้า 404 เวลา Refresh
        proxy_intercept_errors on;
        error_page 404 = /index.html;
    }
}

